spring.application.name=PateintService


spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Every time my app starts, run my SQL setup files.
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=4001
